[build]
  publish = ".next"
  command = "npm install --legacy-peer-deps && npm run build"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true