[build]
  base = "stroop-game-main"
  publish = "out"
  command = "npm install --legacy-peer-deps && npm run build && npm run export"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true